### ISSUE TITLE
setDescription() not defined

### ISSUE THREAD

**Issue by abkrim** [ulrichsg/getopt-php#48]
Hi.

According your manual for set description for options:
```php
new Option('h', 'help')->setDescription('Show help text')
```
But when use get a error and also my IDE phpStorm show me setDescription() undefined. But i see this public function on Option class.
```bash
PHP Fatal error:  Call to undefined function setDescription() 
````
Code my test:
```php
require __DIR__.'/../../vendor/autoload.php';
use Ulrichsg\Getopt\Getopt;
use Ulrichsg\Getopt\Option;
$getOpt = new Getopt(array(
    new Option('u', 'user', Getopt::REQUIRED_ARGUMENT),
    new Option('t', 'type_restore', Getopt::REQUIRED_ARGUMENT),
    new Option('d', 'rsync_delete'),
    new Option(null, 'help'),
    new Option(null, 'version')->setDescription('Show version')
 ));
```
Apreciate help

**Comment by ulrichsg** [comment]
Hi,
which PHP version are you using? The `new Foo()->bar()` syntax is only supported in 5.4 and above. If you are on 5.3, you will have to do it in two steps:

```php
$option = new Option('h', 'help');
$option->setDescription('Show help text');
```

**Comment by abkrim** [comment]
PHP 5.4.40 (cli) (built: Apr 21 2015 19:11:09) 

But phpStomr show "Undefined function setDescription" also if put on two steeps

     $option->setDescription('Show help text');

Also i don't understand well, how to put model 2 steps on array... try several ways, and not work.

Best regards

**Comment by ulrichsg** [comment]
I got it to work by enclosing the `new` statement in parentheses, like this:
```
$getOpt = new Getopt(array(
    // snip
    (new Option(null, 'version'))->setDescription('Show version')
 ));
```
Looks like I need to fix the documentation. Thanks for the heads-up.

**Comment by abkrim** [comment]
A lot of thanks. Work fine.
